version: "3"
services:
  test:
    image: fpipita/puppeteester
    ports:
      - "9229:9229" # puppeteer Node process code
      - "9222:9222" # Chrome containerized instance
      - "40000:3000" # Express server
    volumes:
      - ./src:/src
      - ./node_modules:/node_modules
    environment:
      MOCHA_UI: "bdd"
