version: "3.7"
services:
  test:
    image: fpipita/puppeteester
    ports:
      - "9229:9229" # puppeteer Node process code
      - "9222:9222" # Chrome containerized instance
      - "40000:3000" # Express server
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: bind
        source: ./node_modules
        target: /node_modules
    environment:
      # takes one of Mocha's supported interfaces
      UI: "tdd"
      # simulate running specs on a lg device
      BROWSER_OPTIONS: '{"defaultViewport":{"width":1280,"height":720}}'
      # you can choose between "watch" (default) and "ci" modes
      # ci mode runs the tests once and exits with either code 0
      # on success or 1 if any test failed
      MODE: "ci"
      # defaults to "false". If set to "true", puppeteester outputs
      # text-summary (to the console) and html coverage reports (to the
      # /coverage volume).
      # You can inspect the html report by pointing your browser to
      # http://localhost:3000/coverage/
      COVERAGE: "true"
