sudo: required

services:
  - docker

script:
  - docker build -t fpipita/puppeteester .
  - docker run -v $(pwd):/puppeteester --workdir /puppeteester fpipita/puppeteester sh -c "npm install && npm test"
