version: "3.7"
services:
  dev-container:
    build: .
    user: "node"
    working_dir: "/home/node/puppeteester"
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    volumes:
      - "${PWD}:/home/node/puppeteester"
    ports:
      - "9223:9222"
      - "9230:9229"
